name: Cancel Previous Runs

on: push

jobs:
  cancel:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          workflow_id: >-
            benchmark.yml,
            examples.yml,
            test.yml,
            test_coverage.yml,
            test_install.yml,
            publish.yml
          access_token: ${{ github.token }}
